version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    groups:
      gha:
        patterns: ["*"]
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "wasm-bindgen" # must be coordinated with nix updates
    groups:
      cargo-deps:
        patterns: ["*"]
  - package-ecosystem: "nix"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 0
    groups:
      flake-inputs:
        patterns: ["*"]
