name = "nix-cache-rs"
main = "build/worker/shim.mjs"
compatibility_date = "2026-05-28"

[build]
command = "worker-build --release"

[vars]
cache_endpoint = "https://nix-cache-rs.philippe-e68.workers.dev" # catch-22: we can only know this after deploying the worker
bucket_name = "nix-cache-test"
github_username = "plaflamme"

[secrets]
required = ["R2_ENDPOINT", "R2_ACCESS_KEY_ID", "R2_SECRET_ACCESS_KEY"]

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = true
persist = true
head_sampling_rate = 1

[[r2_buckets]]
bucket_name = "nix-cache-test"
binding = "nix-cache-bucket"
